<?php
/**
 * Created by PhpStorm.
 * @author Danilo Cavalcanti de Moura
 * Email: danilo-cm@hotmail.com
 */
?>
<?php if ($block->isEnableBanner()): ?>
<div id="container-banner-ebit">
    <param id="ebitParam" value="<?= $block->getValueEbitParam(); ?>" />
    <a id="bannerEbit"></a>
    <script type="text/javascript" id="getSelo" src="https://imgs.ebit.com.br/ebitBR/selo-ebit/js/getSelo.js?<?= $block->getStoreEbit(); ?><?= ($block->showLightbox()) ? '&lightbox=true' : '&lightbox=false' ?>"></script>
</div>
<?php endif;?>
